name: Python Linting

on:
  push:
  pull_request:
  schedule:
    # Runs every 7 days at midnight UTC
    - cron: '0 0 */7 * *'

jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python Dependencies
      run: npm run lint:install

    - name: Lint Python Code
      run: npm run lint
