name: Python Linting

on:
  push:
  pull_request:
  schedule:
    # Runs every 30 days at midnight UTC
    - cron: '0 0 */30 * *'

jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python Deps
      run: npm run lint:install

    - name: Lint Scripts
      run: npm run lint
